import { Subject } from '@/lib/types'

export const SUBJECTS: Subject[] = [
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    slug: 'cybersecurity',
    icon: '🛡️',
    color: '#ef4444',
    description: 'Incident response, threat hunting, forensics, and vulnerability assessment',
    topics: [
      { id: 'incident-response', subjectId: 'cybersecurity', name: 'Incident Response', slug: 'incident-response', description: 'Detect, contain, and recover from security incidents', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'threat-hunting', subjectId: 'cybersecurity', name: 'Threat Hunting', slug: 'threat-hunting', description: 'Proactively search for hidden threats in your environment', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'malware-analysis', subjectId: 'cybersecurity', name: 'Malware Analysis', slug: 'malware-analysis', description: 'Analyze and understand malicious software behavior', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'vulnerability-assessment', subjectId: 'cybersecurity', name: 'Vulnerability Assessment', slug: 'vulnerability-assessment', description: 'Identify and prioritize security weaknesses', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'digital-forensics', subjectId: 'cybersecurity', name: 'Digital Forensics', slug: 'digital-forensics', description: 'Collect and analyze digital evidence from compromised systems', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
    ],
  },
  {
    id: 'networking',
    name: 'Networking',
    slug: 'networking',
    icon: '🌐',
    color: '#3b82f6',
    description: 'Network troubleshooting, routing, switching, and security',
    topics: [
      { id: 'network-troubleshooting', subjectId: 'networking', name: 'Network Troubleshooting', slug: 'network-troubleshooting', description: 'Diagnose and fix network outages and performance issues', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'routing-protocols', subjectId: 'networking', name: 'Routing Protocols', slug: 'routing-protocols', description: 'Configure and troubleshoot OSPF, BGP, and static routes', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'network-security', subjectId: 'networking', name: 'Network Security', slug: 'network-security', description: 'Firewalls, ACLs, VPNs, and intrusion detection', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'wireless-networking', subjectId: 'networking', name: 'Wireless Networking', slug: 'wireless-networking', description: 'Design and secure wireless networks', difficultyLevels: ['beginner', 'intermediate'] },
      { id: 'network-design', subjectId: 'networking', name: 'Network Design', slug: 'network-design', description: 'Plan and implement scalable network architectures', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
    ],
  },
  {
    id: 'linux',
    name: 'Linux',
    slug: 'linux',
    icon: '🐧',
    color: '#f59e0b',
    description: 'Server administration, scripting, performance tuning, and hardening',
    topics: [
      { id: 'system-administration', subjectId: 'linux', name: 'System Administration', slug: 'system-administration', description: 'Manage users, services, and system resources', difficultyLevels: ['beginner', 'intermediate'] },
      { id: 'bash-scripting', subjectId: 'linux', name: 'Bash Scripting', slug: 'bash-scripting', description: 'Write automation scripts and solve problems with bash', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'performance-tuning', subjectId: 'linux', name: 'Performance Tuning', slug: 'performance-tuning', description: 'Diagnose and fix system performance bottlenecks', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'security-hardening', subjectId: 'linux', name: 'Security Hardening', slug: 'security-hardening', description: 'Harden Linux systems against attacks', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'service-management', subjectId: 'linux', name: 'Service Management', slug: 'service-management', description: 'Configure and troubleshoot systemd services and daemons', difficultyLevels: ['beginner', 'intermediate'] },
    ],
  },
  {
    id: 'cloud-computing',
    name: 'Cloud Computing',
    slug: 'cloud-computing',
    icon: '☁️',
    color: '#6366f1',
    description: 'Cloud security, cost optimization, IaC, and architecture',
    topics: [
      { id: 'cloud-security', subjectId: 'cloud-computing', name: 'Cloud Security', slug: 'cloud-security', description: 'Identify and fix cloud misconfigurations and security findings', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'cost-optimization', subjectId: 'cloud-computing', name: 'Cost Optimization', slug: 'cost-optimization', description: 'Analyze and reduce cloud spending without losing performance', difficultyLevels: ['beginner', 'intermediate'] },
      { id: 'infrastructure-as-code', subjectId: 'cloud-computing', name: 'Infrastructure as Code', slug: 'infrastructure-as-code', description: 'Write and fix Terraform and CloudFormation templates', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'cloud-architecture', subjectId: 'cloud-computing', name: 'Cloud Architecture', slug: 'cloud-architecture', description: 'Design scalable, resilient cloud systems', difficultyLevels: ['advanced', 'expert'] },
      { id: 'serverless', subjectId: 'cloud-computing', name: 'Serverless Computing', slug: 'serverless', description: 'Build and debug serverless functions and event-driven systems', difficultyLevels: ['intermediate', 'advanced'] },
    ],
  },
  {
    id: 'ai-ml',
    name: 'AI & Machine Learning',
    slug: 'ai-ml',
    icon: '🤖',
    color: '#8b5cf6',
    description: 'Model debugging, data quality, bias detection, and pipeline fixes',
    topics: [
      { id: 'model-debugging', subjectId: 'ai-ml', name: 'Model Debugging', slug: 'model-debugging', description: 'Diagnose why models perform poorly and fix them', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'data-quality', subjectId: 'ai-ml', name: 'Data Quality', slug: 'data-quality', description: 'Identify and fix data pipeline issues and bad data', difficultyLevels: ['beginner', 'intermediate'] },
      { id: 'bias-detection', subjectId: 'ai-ml', name: 'Bias Detection', slug: 'bias-detection', description: 'Detect, measure, and mitigate bias in ML models', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'model-evaluation', subjectId: 'ai-ml', name: 'Model Evaluation', slug: 'model-evaluation', description: 'Choose the right metrics and interpret model performance', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'mlops', subjectId: 'ai-ml', name: 'MLOps', slug: 'mlops', description: 'Deploy, monitor, and maintain models in production', difficultyLevels: ['advanced', 'expert'] },
    ],
  },
  {
    id: 'software-development',
    name: 'Software Development',
    slug: 'software-development',
    icon: '💻',
    color: '#10b981',
    description: 'Debugging, code review, feature implementation, and security',
    topics: [
      { id: 'debugging', subjectId: 'software-development', name: 'Debugging', slug: 'debugging', description: 'Find and fix bugs in real codebases', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'security-vulnerabilities', subjectId: 'software-development', name: 'Security Vulnerabilities', slug: 'security-vulnerabilities', description: 'Identify and fix common security vulnerabilities in code', difficultyLevels: ['intermediate', 'advanced', 'expert'] },
      { id: 'code-review', subjectId: 'software-development', name: 'Code Review', slug: 'code-review', description: 'Review code for quality, performance, and correctness', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'api-development', subjectId: 'software-development', name: 'API Development', slug: 'api-development', description: 'Design and implement REST APIs correctly', difficultyLevels: ['beginner', 'intermediate', 'advanced'] },
      { id: 'testing', subjectId: 'software-development', name: 'Testing', slug: 'testing', description: 'Write unit, integration, and end-to-end tests', difficultyLevels: ['beginner', 'intermediate'] },
    ],
  },
  {
    id: 'systems-administration',
    name: 'Systems Administration',
    slug: 'systems-administration',
    icon: '⚙️',
    color: '#f97316',
    description: 'System performance, service failures, monitoring, and automation',
    topics: [
      { id: 'performance-monitoring', subjectId: 'systems-administration', name: 'Performance Monitoring', slug: 'performance-monitoring', description: 'Set up monitoring and diagnose performance bottlenecks', difficultyLevels: ['beginner', 'intermediate'] },
      { id: 'service-recovery', subjectId: 'systems-administration', name: 'Service Recovery', slug: 'service-recovery', description: 'Restore failed services quickly and safely', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'backup-recovery', subjectId: 'systems-administration', name: 'Backup & Recovery', slug: 'backup-recovery', description: 'Implement and test backup and disaster recovery plans', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'automation', subjectId: 'systems-administration', name: 'Automation', slug: 'automation', description: 'Automate repetitive tasks with scripts and configuration management', difficultyLevels: ['intermediate', 'advanced'] },
      { id: 'capacity-planning', subjectId: 'systems-administration', name: 'Capacity Planning', slug: 'capacity-planning', description: 'Plan and scale infrastructure to meet demand', difficultyLevels: ['advanced', 'expert'] },
    ],
  },
]

export const SUBJECT_QUESTIONS: Record<string, Array<{ id: string; question: string; type: 'select' | 'text'; options?: string[] }>> = {
  cybersecurity: [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Identify attack vectors', 'Trace lateral movement', 'Scope a breach', 'Write an incident report', 'Recommend remediation'] },
    { id: 'incident_type', question: 'What type of incident should the scenario involve?', type: 'select', options: ['Ransomware attack', 'Data exfiltration', 'Phishing compromise', 'Insider threat', 'Supply chain attack', 'Zero-day exploit'] },
    { id: 'tools', question: 'What tools should students use?', type: 'select', options: ['Log files only', 'Log files + network captures', 'System memory dumps', 'All forensic tools'] },
    { id: 'technologies', question: 'Any specific technologies to include?', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
  networking: [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Diagnose outage', 'Fix misconfiguration', 'Improve performance', 'Secure the network', 'Design topology'] },
    { id: 'scenario_type', question: 'What type of network problem should occur?', type: 'select', options: ['Complete outage', 'Intermittent connectivity', 'Performance degradation', 'Security breach', 'Routing loop'] },
    { id: 'devices', question: 'What devices should be in the scenario?', type: 'select', options: ['Routers + switches', 'Firewalls included', 'Wireless APs included', 'Full enterprise stack'] },
    { id: 'protocols', question: 'Any specific protocols to focus on?', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
  linux: [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Fix a broken service', 'Write an automation script', 'Harden the system', 'Diagnose performance', 'Manage users and permissions'] },
    { id: 'scenario_type', question: 'What type of situation should the scenario involve?', type: 'select', options: ['Production server emergency', 'Scheduled maintenance gone wrong', 'Security incident', 'Performance crisis', 'New server setup'] },
    { id: 'distro', question: 'Which Linux distribution?', type: 'select', options: ['Ubuntu', 'CentOS/RHEL', 'Debian', 'Any (distro-agnostic)'] },
    { id: 'services', question: 'Any specific services to include? (e.g. Apache, MySQL, SSH)', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
  'cloud-computing': [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Identify misconfiguration', 'Fix security issue', 'Optimise cost', 'Implement IaC fix', 'Design architecture'] },
    { id: 'provider', question: 'Which cloud provider?', type: 'select', options: ['AWS', 'Azure', 'GCP', 'Multi-cloud / generic'] },
    { id: 'scenario_type', question: 'What type of problem?', type: 'select', options: ['Security misconfiguration', 'Cost overrun', 'Outage post-deploy', 'Compliance violation', 'Performance issue'] },
    { id: 'services', question: 'Any specific cloud services to include?', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
  'ai-ml': [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Diagnose poor model performance', 'Fix data pipeline', 'Improve accuracy', 'Detect and fix bias', 'Document findings'] },
    { id: 'problem_type', question: 'What type of ML problem?', type: 'select', options: ['Classification', 'Regression', 'NLP', 'Computer vision', 'Recommendation system'] },
    { id: 'scenario_type', question: 'What went wrong in the scenario?', type: 'select', options: ['Model accuracy dropped in production', 'Training data is corrupted', 'Model is biased against a group', 'Pipeline is failing', 'Predictions are drifting'] },
    { id: 'tools', question: 'Any specific tools or frameworks?', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
  'software-development': [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Find and fix a bug', 'Fix a security vulnerability', 'Implement a feature', 'Improve performance', 'Write tests'] },
    { id: 'language', question: 'Which programming language?', type: 'select', options: ['Python', 'JavaScript/Node.js', 'Java', 'Go', 'Any'] },
    { id: 'scenario_type', question: 'What type of situation?', type: 'select', options: ['Production bug reported by user', 'Security audit finding', 'Code review with issues', 'Feature with failing tests', 'Performance regression'] },
    { id: 'technologies', question: 'Any specific frameworks or technologies?', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
  'systems-administration': [
    { id: 'objective', question: 'What is the main learning objective?', type: 'select', options: ['Diagnose bottleneck', 'Restore a service', 'Set up monitoring', 'Automate a task', 'Plan capacity'] },
    { id: 'scenario_type', question: 'What type of situation?', type: 'select', options: ['After-hours outage', 'Gradual performance decline', 'Scheduled task failing', 'New system deployment', 'Disaster recovery drill'] },
    { id: 'os', question: 'Which operating system?', type: 'select', options: ['Linux (Ubuntu/Debian)', 'Linux (RHEL/CentOS)', 'Windows Server', 'Mixed environment'] },
    { id: 'tools', question: 'Any specific monitoring or automation tools?', type: 'text' },
    { id: 'skills', question: 'Any specific skills to assess?', type: 'text' },
  ],
}
